// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function toAssesment(str) {
  if (str === "CORRECT") {
    return /* Correct */0;
  } else {
    return /* Incorrect */1;
  }
}

function answer(json) {
  return {
          fingerprint: Json_decode.field("fingerprint", Json_decode.string, json),
          question_id: Json_decode.field("question_id", Json_decode.$$int, json),
          assesment: toAssesment(Json_decode.field("assesment", Json_decode.string, json))
        };
}

var Decode = {
  toAssesment: toAssesment,
  answer: answer
};

function assesmentToStr(a) {
  if (a === /* Correct */0) {
    return "CORRECT";
  } else {
    return "INCORRECT";
  }
}

function answer$1(a) {
  return Json_encode.object_({
              hd: [
                "fingerprint",
                a.fingerprint
              ],
              tl: {
                hd: [
                  "question_id",
                  a.question_id
                ],
                tl: {
                  hd: [
                    "assesment",
                    assesmentToStr(a.assesment)
                  ],
                  tl: /* [] */0
                }
              }
            });
}

var Encode = {
  assesmentToStr: assesmentToStr,
  answer: answer$1
};

exports.Decode = Decode;
exports.Encode = Encode;
/* No side effect */
