// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Express = require("bs-express/src/Express.bs.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var AnswerController$Avocardo = require("./answers/AnswerController.bs.js");
var PronounController$Avocardo = require("./exercises/PronounController.bs.js");

function makeSuccessJson(response) {
  var json = {};
  json["success"] = true;
  json["data"] = response;
  return json;
}

function handleAnswer(req, res) {
  return AnswerController$Avocardo.genSave(Belt_Option.getExn(Express.$$Request.bodyJSON(req))).then(function (param) {
              return Promise.resolve(Express.$$Response.sendJson(makeSuccessJson(1), res));
            });
}

function handlePronounExercises(param, res) {
  return PronounController$Avocardo.genJsonResponse(undefined).then(function (json) {
              return Promise.resolve(Express.$$Response.sendJson(makeSuccessJson(json), res));
            });
}

exports.makeSuccessJson = makeSuccessJson;
exports.handleAnswer = handleAnswer;
exports.handlePronounExercises = handlePronounExercises;
/* Express Not a pure module */
