// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("rescript/lib/js/string.js");
var $$Crypto = require("crypto");

var $$Crypto$1 = {};

function gen(param) {
  var randomPool = Buffer.from($$String.make(32, /* 'c' */99));
  return $$Crypto.randomFillSync(randomPool).toString("base64");
}

exports.$$Crypto = $$Crypto$1;
exports.gen = gen;
/* crypto Not a pure module */
