// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("rescript/lib/js/array.js");
var $$String = require("rescript/lib/js/string.js");

function join(classNames) {
  return $$String.concat(" ", $$Array.to_list(classNames));
}

var noop = "noop";

exports.join = join;
exports.noop = noop;
/* No side effect */
