// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("rescript/lib/js/array.js");
var $$String = require("rescript/lib/js/string.js");
var CoreModuleCss = require("./Core.module.css");

var index = CoreModuleCss;

function join(classNames) {
  return $$String.concat(" ", $$Array.to_list(classNames));
}

var noop = "noop";

exports.index = index;
exports.join = join;
exports.noop = noop;
/* index Not a pure module */
