// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("rescript/lib/js/array.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var $$String = require("rescript/lib/js/string.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var Token$Avocardo = require("./Token.bs.js");
var Words$Avocardo = require("./Words.bs.js");
var Prompt$Avocardo = require("./Prompt.bs.js");
var CardModuleCss = require("./Card.module.css");
var Keyboard$Avocardo = require("./hooks/Keyboard.bs.js");

var style = CardModuleCss;

function contains(translations, w) {
  return $$Array.exists((function (t) {
                if (t.TAG === /* Right */0) {
                  return Words$Avocardo.is_match(t._0, w);
                } else {
                  return false;
                }
              }), translations);
}

function solution(exercise) {
  var findRight = function (opts, _idx) {
    while(true) {
      var idx = _idx;
      var str = Caml_array.get(opts, idx);
      if (str.TAG === /* Right */0) {
        return str._0;
      }
      _idx = idx + 1 | 0;
      continue ;
    };
  };
  return findRight(exercise.pronouns, 0) + (" " + findRight(exercise.nouns, 0));
}

function solved(selection, exercise) {
  var tokens = $$String.split_on_char(/* ' ' */32, $$String.trim(selection));
  if (!tokens) {
    return false;
  }
  var match = tokens.tl;
  if (match && !(match.tl || !contains(exercise.pronouns, tokens.hd))) {
    return contains(exercise.nouns, match.hd);
  } else {
    return false;
  }
}

var ExerciseSolver = {
  contains: contains,
  solution: solution,
  solved: solved
};

function Card$Result(Props) {
  var exercise = Props.exercise;
  return React.createElement("div", {
              className: style.result
            }, React.createElement("div", {
                  className: style["result-quiz"]
                }, exercise.quiz), React.createElement("div", {
                  className: style["result-solution"]
                }, solution(exercise)));
}

var Result = {
  make: Card$Result
};

function Card$Evaluation(Props) {
  var selection = Props.selection;
  var exercise = Props.exercise;
  return React.createElement("div", {
              className: style.app
            }, solved(selection, exercise) ? React.createElement(React.Fragment, undefined, React.createElement("span", {
                        className: style.result
                      }, "You got it!"), React.createElement("img", {
                        className: style["result-avocado"],
                        src: "/img/success.jpg"
                      })) : React.createElement(React.Fragment, undefined, React.createElement(Card$Result, {
                        exercise: exercise
                      }), React.createElement("img", {
                        className: style["result-avocado"],
                        src: "/img/failure.jpg"
                      })));
}

var Evaluation = {
  make: Card$Evaluation
};

function reduce_quiz(state, action) {
  if (typeof action === "number") {
    if (action !== 0) {
      if (state.TAG === /* Solving */0) {
        return {
                TAG: 0,
                _0: "",
                [Symbol.for("name")]: "Solving"
              };
      } else {
        return state;
      }
    } else if (state.TAG === /* Solving */0) {
      return {
              TAG: 1,
              _0: state._0,
              [Symbol.for("name")]: "Veredict"
            };
    } else {
      return {
              TAG: 0,
              _0: "",
              [Symbol.for("name")]: "Solving"
            };
    }
  } else if (state.TAG === /* Solving */0) {
    return {
            TAG: 0,
            _0: state._0 + action._0,
            [Symbol.for("name")]: "Solving"
          };
  } else {
    return state;
  }
}

function willRestartQuiz(cur, next) {
  if (cur.TAG === /* Solving */0 || next.TAG !== /* Solving */0) {
    return false;
  } else {
    return true;
  }
}

function willShowVeredict(cur, next) {
  if (cur.TAG === /* Solving */0 && next.TAG !== /* Solving */0) {
    return true;
  } else {
    return false;
  }
}

function Card(Props) {
  var exercise = Props.exercise;
  var next = Props.next;
  var storeStatus = Props.storeStatus;
  var filter = Props.filter;
  var match = React.useState(function () {
        return {
                TAG: 0,
                _0: "",
                [Symbol.for("name")]: "Solving"
              };
      });
  var setQuiz = match[1];
  var quiz = match[0];
  var e = Curry._1(exercise.read, undefined);
  Keyboard$Avocardo.use(React.useCallback(function (c) {
            var a = {
              _0: c,
              [Symbol.for("name")]: "Char"
            };
            return Curry._1(setQuiz, (function (s) {
                          return reduce_quiz(s, a);
                        }));
          }), React.useCallback((function (param) {
              var match = reduce_quiz(quiz, /* Enter */0);
              if (quiz.TAG === /* Solving */0) {
                if (match.TAG !== /* Solving */0) {
                  Curry._2(storeStatus, e, solved(match._0, e));
                }
                
              } else if (match.TAG === /* Solving */0) {
                Curry._1(next, undefined);
              }
              return Curry._1(setQuiz, (function (s) {
                            return reduce_quiz(s, /* Enter */0);
                          }));
            }), [
            quiz,
            next
          ]), React.useCallback(function (param) {
            return Curry._1(setQuiz, (function (s) {
                          return reduce_quiz(s, /* Delete */1);
                        }));
          }));
  if (quiz.TAG !== /* Solving */0) {
    return React.createElement(Card$Evaluation, {
                selection: quiz._0,
                exercise: e
              });
  }
  var selection = quiz._0;
  var match$1 = Token$Avocardo.StyledWords.style(selection, e.pronouns, e.nouns);
  return React.createElement("div", {
              className: style.app
            }, React.createElement("div", {
                  className: style.filter
                }, filter), React.createElement("div", {
                  className: style.challenge
                }, e.quiz), React.createElement("div", {
                  className: style.input
                }, selection, React.createElement(Prompt$Avocardo.make, {})), React.createElement("div", {
                  className: style.options
                }, React.createElement("div", {
                      className: style.column
                    }, $$Array.map((function (tok) {
                            return React.createElement(Token$Avocardo.make, {
                                        tok: tok
                                      });
                          }), match$1[0])), React.createElement("div", {
                      className: style.column
                    }, $$Array.map((function (tok) {
                            return React.createElement(Token$Avocardo.make, {
                                        tok: tok
                                      });
                          }), match$1[1]))));
}

var make = Card;

exports.style = style;
exports.ExerciseSolver = ExerciseSolver;
exports.Result = Result;
exports.Evaluation = Evaluation;
exports.reduce_quiz = reduce_quiz;
exports.willRestartQuiz = willRestartQuiz;
exports.willShowVeredict = willShowVeredict;
exports.make = make;
/* style Not a pure module */
