// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Js_dict = require("rescript/lib/js/js_dict.js");
var ServerFingerprint$Avocardo = require("./auth/ServerFingerprint.bs.js");

function IndexRes$P(Props) {
  var hell = Props.hell;
  return React.createElement("div", undefined, "Hello from rescript and next " + hell);
}

var P = {
  make: IndexRes$P
};

function $$default(props) {
  return React.createElement(IndexRes$P, {
              hell: props.hell
            });
}

function getServerSideProps(ctx) {
  var cookies = ctx.req.cookies;
  var fp = Js_dict.get(cookies, "fingerprint");
  var fingerprint;
  if (fp !== undefined) {
    fingerprint = fp;
  } else {
    var fp$1 = ServerFingerprint$Avocardo.gen(undefined);
    ctx.res.setHeader("Set-Cookie", "fingerprint=" + fp$1 + "; SameSite=Strict; Expires=Wed, 21 Oct 2021 07:28:00 GMT");
    fingerprint = fp$1;
  }
  console.log(cookies);
  return Promise.resolve({
              props: {
                hell: fingerprint
              }
            });
}

exports.P = P;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.getServerSideProps = getServerSideProps;
/* react Not a pure module */
