// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var UI$Avocardo = require("./UI.bs.js");
var ExerciseQueryManager$Avocardo = require("./ExerciseQueryManager.bs.js");

function IndexRes$P(Props) {
  var fingerprint = Props.fingerprint;
  var isServer = (function isServer() {
              return typeof window === 'undefined';
            });
  if (Curry._1(isServer, undefined)) {
    return null;
  } else {
    return React.createElement(UI$Avocardo.App.make, {
                initialQM: ExerciseQueryManager$Avocardo.make(fingerprint)
              });
  }
}

var P = {
  make: IndexRes$P
};

function $$default(props) {
  return React.createElement(IndexRes$P, {
              fingerprint: props.fingerprint
            });
}

exports.P = P;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
