// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var style = {
  backgroundColor: "currentcolor",
  display: "inline-block",
  height: "11px",
  marginLeft: "1px",
  verticalAlign: "middle",
  width: "6px"
};

function Prompt(Props) {
  return React.createElement("span", {
              style: style
            });
}

var make = Prompt;

exports.style = style;
exports.make = make;
/* react Not a pure module */
