// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-dom/src/Css.js");
var React = require("react");

var style = Css.style({
      hd: Css.height({
            NAME: "px",
            VAL: 11
          }),
      tl: {
        hd: Css.width({
              NAME: "px",
              VAL: 6
            }),
        tl: {
          hd: Css.backgroundColor("currentColor"),
          tl: {
            hd: Css.display(Css.inlineBlock),
            tl: {
              hd: Css.marginLeft(Css.px(1)),
              tl: {
                hd: Css.verticalAlign(Css.middle),
                tl: /* [] */0
              }
            }
          }
        }
      }
    });

function Prompt(Props) {
  return React.createElement("span", {
              style: style
            });
}

var make = Prompt;

exports.style = style;
exports.make = make;
/* style Not a pure module */
