// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var app = {
  display: "grid",
  height: "200px",
  width: "200px",
  gridTemplateColumns: "repeat(3, 1fr)"
};

var center = {
  gridColumn: "2 2",
  gridRow: "2 2"
};

var Styles = {
  app: app,
  center: center
};

function Shimmer(Props) {
  return React.createElement("div", {
              style: app
            }, React.createElement("span", {
                  style: center
                }, "Loading..."));
}

var make = Shimmer;

exports.Styles = Styles;
exports.make = make;
/* react Not a pure module */
