// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ShimmerModuleCss = require("./Shimmer.module.css");

var style = ShimmerModuleCss;

function Shimmer(Props) {
  return React.createElement("div", {
              className: style.app
            }, React.createElement("span", {
                  className: style.shimmer
                }, "Loading..."));
}

var make = Shimmer;

exports.style = style;
exports.make = make;
/* style Not a pure module */
