// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-dom/src/Css.js");
var React = require("react");

var app = Css.style({
      hd: Css.height({
            NAME: "px",
            VAL: 200
          }),
      tl: {
        hd: Css.width({
              NAME: "px",
              VAL: 200
            }),
        tl: {
          hd: Css.display("grid"),
          tl: {
            hd: Css.gridTemplateColumns({
                  hd: {
                    NAME: "repeat",
                    VAL: [
                      {
                        NAME: "num",
                        VAL: 3
                      },
                      {
                        NAME: "fr",
                        VAL: 1
                      }
                    ]
                  },
                  tl: /* [] */0
                }),
            tl: {
              hd: Css.gridGap({
                    NAME: "px",
                    VAL: 10
                  }),
              tl: {
                hd: Css.gridAutoRows({
                      NAME: "minmax",
                      VAL: [
                        {
                          NAME: "px",
                          VAL: 50
                        },
                        "auto"
                      ]
                    }),
                tl: /* [] */0
              }
            }
          }
        }
      }
    });

var center = Css.style({
      hd: Css.gridColumn(2, 2),
      tl: {
        hd: Css.gridRow(2, 2),
        tl: /* [] */0
      }
    });

var Styles = {
  app: app,
  center: center
};

function Shimmer(Props) {
  return React.createElement("div", {
              style: app
            }, React.createElement("span", {
                  style: center
                }, "Loading..."));
}

var make = Shimmer;

exports.Styles = Styles;
exports.make = make;
/* app Not a pure module */
