// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function make(p) {
  var status = {
    contents: /* Loading */0
  };
  p.then(function (e) {
        status.contents = {
          _0: e,
          [Symbol.for("name")]: "Succeed"
        };
        return Promise.resolve(e);
      });
  return {
          read: (function (param) {
              var e = status.contents;
              if (typeof e !== "number") {
                return e._0;
              }
              if (e !== 0) {
                throw {
                      RE_EXN_ID: "Not_found",
                      Error: new Error()
                    };
              }
              return Curry._1((function fn() {
              throw p;
            }), undefined);
            })
        };
}

function $$const(c) {
  return make(Promise.resolve(c));
}

exports.make = make;
exports.$$const = $$const;
/* No side effect */
