// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function waitMS(delay) {
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(undefined);
                      }), delay);
                
              }));
}

exports.waitMS = waitMS;
/* No side effect */
