// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("rescript/lib/js/array.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var $$String = require("rescript/lib/js/string.js");
var Words$Avocardo = require("./Words.bs.js");
var TokenModuleCss = require("./Token.module.css");
var PronounExercises$Avocardo = require("../server/exercises/PronounExercises.bs.js");

var style = TokenModuleCss;

var bold = {
  fontWeight: "bold"
};

var noop = {};

function token(pct) {
  var begin_rgb = [
    223,
    223,
    226
  ];
  var get_delta = function (param, param$1) {
    return [
            param$1[0] - param[0],
            param$1[1] - param[1],
            param$1[2] - param[2]
          ];
  };
  var scale = function (param, param$1, pct) {
    return [
            param[0] + param$1[0] * pct,
            param[1] + param$1[1] * pct,
            param[2] + param$1[2] * pct
          ];
  };
  var match = scale(begin_rgb, get_delta(begin_rgb, [
            180,
            206,
            141
          ]), pct);
  return {
          backgroundColor: "rgb(" + String(match[0] | 0) + ", " + String(match[1] | 0) + ", " + String(match[2] | 0) + ")"
        };
}

var Styles = {
  bold: bold,
  noop: noop,
  token: token
};

function create(word, matchedPrefix) {
  return {
          tokens: matchedPrefix !== 0 ? (
              matchedPrefix >= word.length ? [[
                    word,
                    true
                  ]] : [
                  [
                    $$String.sub(word, 0, matchedPrefix),
                    true
                  ],
                  [
                    $$String.sub(word, matchedPrefix, word.length - matchedPrefix | 0),
                    false
                  ]
                ]
            ) : [[
                word,
                false
              ]],
          pct_match: word.length === 0 ? 0 : matchedPrefix / word.length
        };
}

function map(fn, tok) {
  return $$Array.map((function (param) {
                return Curry._2(fn, param[0], param[1] ? bold : noop);
              }), tok.tokens);
}

function style$1(tok) {
  return token(tok.pct_match);
}

var StyledToken = {
  create: create,
  map: map,
  style: style$1
};

function match_(words, prefix) {
  return $$Array.map((function (w) {
                return create(w, Words$Avocardo.max_prefix(w, prefix));
              }), $$Array.map(PronounExercises$Avocardo.toString, words));
}

function style$2(word, pronouns, candidates) {
  var tokens = $$String.split_on_char(/* ' ' */32, word);
  if (!tokens) {
    return [
            match_(pronouns, ""),
            match_(candidates, "")
          ];
  }
  var match = tokens.tl;
  var h = tokens.hd;
  if (match) {
    return [
            match_(pronouns, h),
            match_(candidates, match.hd)
          ];
  } else {
    return [
            match_(pronouns, h),
            match_(candidates, "")
          ];
  }
}

var StyledWords = {
  match_: match_,
  style: style$2
};

function Token(Props) {
  var tok = Props.tok;
  return React.createElement("button", {
              className: style.token,
              style: token(tok.pct_match)
            }, map((function (str, style) {
                    return React.createElement("span", {
                                style: style
                              }, str);
                  }), tok));
}

var make = Token;

exports.style = style;
exports.Styles = Styles;
exports.StyledToken = StyledToken;
exports.StyledWords = StyledWords;
exports.make = make;
/* style Not a pure module */
