// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var PronounExercises$Avocardo = require("../server/exercises/PronounExercises.bs.js");

var get = (function get(m) {
  return process.env.SERVER_DOMAIN;
});

function getDomain(path) {
  var maybeDomain = get(undefined);
  var domain = Belt_Option.getExn(maybeDomain);
  return "" + domain + "/" + path;
}

function getExercise(param) {
  return fetch(getDomain("pronoun_exercises")).then(function (prim) {
                return prim.json();
              }).then(function (txt) {
              return Promise.resolve(Json_decode.field("data", PronounExercises$Avocardo.Decode.exercise, txt));
            });
}

exports.get = get;
exports.getDomain = getDomain;
exports.getExercise = getExercise;
/* No side effect */
