// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var ServerFingerprint$Avocardo = require("../auth/ServerFingerprint.bs.js");

function getServerSideProps(ctx) {
  var cookies = ctx.req.cookies;
  var fp = Js_dict.get(cookies, "fingerprint");
  var fingerprint;
  if (fp !== undefined) {
    fingerprint = fp;
  } else {
    var fp$1 = ServerFingerprint$Avocardo.gen(undefined);
    ctx.res.setHeader("Set-Cookie", "fingerprint=" + fp$1 + "; SameSite=Strict; Expires=Wed, 21 Oct 2021 07:28:00 GMT");
    fingerprint = fp$1;
  }
  return Promise.resolve({
              props: {
                fingerprint: fingerprint
              }
            });
}

exports.getServerSideProps = getServerSideProps;
/* ServerFingerprint-Avocardo Not a pure module */
