// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var RescriptRelay = require("rescript-relay/src/RescriptRelay.bs.js");
var Index$Avocardo = require("../avocardo/Index.bs.js");
var RelayEnv$Avocardo = require("../avocardo/RelayEnv.bs.js");

function IndexRes$P(Props) {
  var fingerprint = Props.fingerprint;
  var isServer = (function isServer() {
              return typeof window === 'undefined';
            });
  if (Curry._1(isServer, undefined)) {
    return null;
  } else {
    return React.createElement(Index$Avocardo.App.make, {
                fingerprint: fingerprint
              });
  }
}

var P = {
  make: IndexRes$P
};

function $$default(props) {
  return React.createElement(RescriptRelay.Context.Provider.make, {
              environment: RelayEnv$Avocardo.environment,
              children: React.createElement(IndexRes$P, {
                    fingerprint: props.fingerprint
                  })
            });
}

exports.P = P;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
