// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function IndexRes$P(Props) {
  return React.createElement("div", undefined, "Hello from rescript and next");
}

var P = {
  make: IndexRes$P
};

function $$default(param) {
  return React.createElement(IndexRes$P, {});
}

exports.P = P;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
