// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var MySql2 = require("bs-mysql2/src/MySql2.bs.js");
var Dotenv = require("dotenv");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Process = require("process");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

Dotenv.config();

function conn(param) {
  return MySql2.Connection.connect(undefined, undefined, "root", Belt_Option.getExn(Js_dict.get(Process.env, "MYSQL_PWD")), "avocardo", undefined);
}

function withConnection(cb) {
  var conn$1 = conn(undefined);
  Curry._1(cb, conn$1);
  return MySql2.Connection.close(conn$1);
}

exports.conn = conn;
exports.withConnection = withConnection;
/*  Not a pure module */
