// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var MySql2 = require("bs-mysql2/src/MySql2.bs.js");

var getPWD = (function() {
    return process.env.MYSQL_PWD;
  });

function conn(param) {
  return MySql2.Connection.connect(undefined, undefined, "root", Curry._1(getPWD, undefined), "avocardo", undefined);
}

function withConnection(cb) {
  var conn$1 = conn(undefined);
  Curry._1(cb, conn$1);
  return MySql2.Connection.close(conn$1);
}

exports.getPWD = getPWD;
exports.conn = conn;
exports.withConnection = withConnection;
/* MySql2 Not a pure module */
