// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var MySql2 = require("bs-mysql2/src/MySql2.bs.js");
var Dotenv = require("dotenv");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Process = require("process");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

Dotenv.config();

var conn = MySql2.Connection.connect(undefined, undefined, "root", Belt_Option.getExn(Js_dict.get(Process.env, "MYSQL_PWD")), "avocardo", undefined);

function getConnection(param) {
  return conn;
}

exports.conn = conn;
exports.getConnection = getConnection;
/*  Not a pure module */
