// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function use(onChar, onEnter, onDelete) {
  React.useEffect(function () {
        var listen = function (param) {
          var key = param.key;
          switch (key) {
            case "Backspace" :
                return Curry._1(onDelete, undefined);
            case "Enter" :
                return Curry._1(onEnter, undefined);
            case "Alt" :
            case "Control" :
            case "Meta" :
            case "Shift" :
            case "Tab" :
                return ;
            default:
              return Curry._1(onChar, key);
          }
        };
        window.addEventListener("keydown", listen);
        return (function (param) {
                  window.removeEventListener("keydown", listen);
                  
                });
      });
  
}

exports.use = use;
/* react Not a pure module */
