// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function getFingerprint(vc) {
  return vc.fingerprint;
}

function make(param) {
  return {
          fingerprint: "hello"
        };
}

exports.getFingerprint = getFingerprint;
exports.make = make;
/* No side effect */
