// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var PromptModuleCss = require("./Prompt.module.css");

var style = PromptModuleCss;

function Prompt(Props) {
  return React.createElement("span", {
              className: style.prompt
            });
}

var make = Prompt;

exports.style = style;
exports.make = make;
/* style Not a pure module */
