// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Cx$Avocardo = require("../core/Cx.bs.js");

function Shimmer(Props) {
  return React.createElement("div", {
              className: Cx$Avocardo.join([
                    Cx$Avocardo.index.app,
                    Cx$Avocardo.index.shimmer
                  ])
            }, React.createElement("span", undefined, "Loading..."));
}

var make = Shimmer;

exports.make = make;
/* react Not a pure module */
