// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml = require("rescript/lib/js/caml.js");
var $$Array = require("rescript/lib/js/array.js");
var Curry = require("rescript/lib/js/curry.js");
var MySql2 = require("bs-mysql2/src/MySql2.bs.js");
var $$String = require("rescript/lib/js/string.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var DB$Avocardo = require("../db/DB.bs.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var RenderQuery$Requery = require("@adnelson/requery/src/RenderQuery.bs.js");
var QueryBuilder$Requery = require("@adnelson/requery/src/QueryBuilder.bs.js");

function row(json) {
  return {
          id: Json_decode.field("id", Json_decode.$$int, json),
          question: Json_decode.field("question", Json_decode.string, json),
          answer: Json_decode.field("answer", Json_decode.string, json),
          alternatives: Json_decode.field("alternatives", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          variant: Json_decode.field("variant", Json_decode.string, json)
        };
}

var Decode = {
  row: row
};

function format(param) {
  var split = function (sentence) {
    var firstBlankspace = $$String.index(sentence, /* ' ' */32);
    return [
            $$String.sub(sentence, 0, firstBlankspace),
            $$String.sub(sentence, firstBlankspace + 1 | 0, (sentence.length - firstBlankspace | 0) - 1 | 0)
          ];
  };
  var dedupe = function (words) {
    $$Array.sort(Caml.caml_string_compare, words);
    var iterator = function (_prev, _idx, _sum) {
      while(true) {
        var sum = _sum;
        var idx = _idx;
        var prev = _prev;
        if (idx === words.length) {
          return sum;
        }
        if (prev === Caml_array.get(words, idx)) {
          _idx = idx + 1 | 0;
          continue ;
        }
        _sum = {
          hd: Caml_array.get(words, idx),
          tl: sum
        };
        _idx = idx + 1 | 0;
        _prev = Caml_array.get(words, idx);
        continue ;
      };
    };
    return $$Array.of_list(iterator("", 0, /* [] */0));
  };
  var transform = function (words, right) {
    var words$1 = dedupe($$Array.append(words, [right]));
    return $$Array.map((function (w) {
                  if (w === right) {
                    return {
                            TAG: 0,
                            _0: w,
                            [Symbol.for("name")]: "Right"
                          };
                  } else {
                    return {
                            TAG: 1,
                            _0: w,
                            [Symbol.for("name")]: "Wrong"
                          };
                  }
                }), words$1);
  };
  var match = split(param.answer);
  var components = $$Array.map(split, param.alternatives);
  return {
          id: param.id,
          quiz: param.question,
          pronouns: transform($$Array.map((function (prim) {
                      return prim[0];
                    }), components), match[0]),
          nouns: transform($$Array.map((function (prim) {
                      return prim[1];
                    }), components), match[1])
        };
}

function randomQuestion(param) {
  return QueryBuilder$Requery.orderBy1(QueryBuilder$Requery.call(Curry._1(QueryBuilder$Requery.fname, "RAND"), /* [] */0), QueryBuilder$Requery.asc, QueryBuilder$Requery.select(QueryBuilder$Requery.from(QueryBuilder$Requery.tableNamed(undefined, "quizzes"), {
                      hd: QueryBuilder$Requery.e(undefined, QueryBuilder$Requery.tcol(Curry._1(QueryBuilder$Requery.tname, "quizzes"), Curry._1(QueryBuilder$Requery.cname, "id"))),
                      tl: {
                        hd: QueryBuilder$Requery.e(undefined, QueryBuilder$Requery.tcol(Curry._1(QueryBuilder$Requery.tname, "quizzes"), Curry._1(QueryBuilder$Requery.cname, "question"))),
                        tl: {
                          hd: QueryBuilder$Requery.e(undefined, QueryBuilder$Requery.tcol(Curry._1(QueryBuilder$Requery.tname, "quizzes"), Curry._1(QueryBuilder$Requery.cname, "answer"))),
                          tl: {
                            hd: QueryBuilder$Requery.e(undefined, QueryBuilder$Requery.tcol(Curry._1(QueryBuilder$Requery.tname, "quizzes"), Curry._1(QueryBuilder$Requery.cname, "alternatives"))),
                            tl: {
                              hd: QueryBuilder$Requery.e(undefined, QueryBuilder$Requery.tcol(Curry._1(QueryBuilder$Requery.tname, "quizzes"), Curry._1(QueryBuilder$Requery.cname, "variant"))),
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    })));
}

function genQuizzes(ids) {
  var inStatement = $$String.concat(", ", $$Array.to_list(ids));
  var query = "\n    select id, question, answer, alternatives \n    from quizzes \n    where id in (" + inStatement + ")\n  ";
  return new Promise((function (resolve, reject) {
                return DB$Avocardo.withConnection(function (conn) {
                            return MySql2.execute(conn, query, undefined, (function (msg) {
                                          var variant = msg.NAME;
                                          if (variant === "Select") {
                                            return resolve(MySql2.Select.rows(msg.VAL));
                                          } else if (variant === "Mutation") {
                                            return reject({
                                                        RE_EXN_ID: "Failure",
                                                        _1: "UNEXPECTED_MUTATION"
                                                      });
                                          } else {
                                            return reject(MySql2.Exn.toExn(msg.VAL));
                                          }
                                        }));
                          });
              }));
}

function genFailures(fingerprint) {
  return new Promise((function (resolve, reject) {
                return DB$Avocardo.withConnection(function (conn) {
                            return MySql2.execute(conn, " select distinct incorrect_answers.question_id as question_id\n          from (\n            select question_id, assesment \n            from answers \n            where \n              fingerprint = \"" + fingerprint + "\"\n              and assesment='INCORRECT'\n          ) AS incorrect_answers \n          left join (\n          select distinct question_id, assesment \n            from answers \n            where \n              fingerprint = \"" + fingerprint + "\" \n              and assesment='CORRECT' \n          ) as correct_answers\n          on incorrect_answers.question_id = correct_answers.question_id\n          where correct_answers.assesment is NULL", undefined, (function (msg) {
                                          var variant = msg.NAME;
                                          if (variant === "Select") {
                                            return resolve(MySql2.Select.rows(msg.VAL));
                                          } else if (variant === "Mutation") {
                                            return reject({
                                                        RE_EXN_ID: "Failure",
                                                        _1: "UNEXPECTED_MUTATION"
                                                      });
                                          } else {
                                            return reject(MySql2.Exn.toExn(msg.VAL));
                                          }
                                        }));
                          });
              }));
}

function genPronounExercise(param) {
  return new Promise((function (resolve, reject) {
                return DB$Avocardo.withConnection(function (conn) {
                            return MySql2.execute(conn, RenderQuery$Requery.Default.select(randomQuestion(undefined)), undefined, (function (msg) {
                                          var variant = msg.NAME;
                                          if (variant === "Select") {
                                            return resolve(row(Caml_array.get(MySql2.Select.rows(msg.VAL), 0)));
                                          } else if (variant === "Mutation") {
                                            return reject({
                                                        RE_EXN_ID: "Failure",
                                                        _1: "UNEXPECTED_MUTATION"
                                                      });
                                          } else {
                                            return reject(MySql2.Exn.toExn(msg.VAL));
                                          }
                                        }));
                          });
              }));
}

exports.Decode = Decode;
exports.format = format;
exports.randomQuestion = randomQuestion;
exports.genQuizzes = genQuizzes;
exports.genFailures = genFailures;
exports.genPronounExercise = genPronounExercise;
/* MySql2 Not a pure module */
